### ISSUE TITLE
 Can you give the superparameters for each node classification dataset? 

### ISSUE THREAD

**Issue by HuizhaoWang** [cszhangzhen/MVPool#1]
Hi, this paper seems good, but I cannot reproduce the reported performance based on given code. 
Especially on some node classification datasets, the difference between the results we reproduce and those given in the paper is huge.
Is there anything that needs extra attention? For example, the number of pooled layers, the pooled ratio of each layer, or other important settings.

**Comment by cszhangzhen** [comment]
Hi,

Thanks for your interest in our work.

The hyper-parameters are updated in README.md, and please noted that the autograd of spspmm is only supported by older version of PyG. You need to use the same version package to achieve the same results.
